spring:
  application:
    name: e-commerce
  
  # Configuración de la base de datos H2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 

  # Configuración de la consola H2
  h2:
    console:
      enabled: true
      path: /h2-console

# http://localhost:8080/h2-console/

